name: todo
description: Helper open source application to add user with ETECSA services
homepage: https://github.com/todo-devs/todo
repository: https://github.com/todo-devs/todo

publish_to: 'none'

version: 2.0.0+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  get_it: ^5.0.3
  json_annotation: ^3.1.1
  theme_provider: ^0.4.0+1
  get: ^3.24.0
  flutter_translate: ^1.6.0
  meta: ^1.2.4
  flutter_translate_annotations: ^1.0.1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  flutter_translate_gen: ^1.2.4
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - config/ussd_codes.json
    - assets/i18n/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
