name: tests
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Action
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run Tests
        run: |
          flutter pub get
          flutter test
      - name: Run Analysis
        uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Scores
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
          CONVENTIONS: ${{ steps.analysis.outputs.conventions }}
          CONVENTIONS_MAX: ${{ steps.analysis.outputs.conventions_max }}
          DOCUMENTATION: ${{ steps.analysis.outputs.documentation }}
          DOCUMENTATION_MAX: ${{ steps.analysis.outputs.documentation_max }}
          PLATFORMS: ${{ steps.analysis.outputs.platforms }}
          PLATFORMS_MAX: ${{ steps.analysis.outputs.platforms_max }}
          ANALYSIS: ${{ steps.analysis.outputs.analysis }}
          ANALYSIS_MAX: ${{ steps.analysis.outputs.analysis_max }}
          DEPENDENCIES: ${{ steps.analysis.outputs.dependencies }}
          DEPENDENCIES_MAX: ${{ steps.analysis.outputs.dependencies_max }}
          NULL_SAFETY: ${{ steps.analysis.outputs.null_safety }}
          NULL_SAFETY_MAX: ${{ steps.analysis.outputs.null_safety_max }}
        run: |
          # if (( $TOTAL < $TOTAL_MAX ))
          # then
          #   exit 1
          # fi
          if (( $CONVENTIONS < $CONVENTIONS_MAX ))
          then
            echo Fail conventions section
            exit 1
          fi
          if (( $DOCUMENTATION < $DOCUMENTATION_MAX ))
          then
            echo Fail documentation section
            exit 1
          fi
          # if (( $PLATFORMS < $PLATFORMS_MAX ))
          # then
          #   echo Fail platforms section
          #   exit 1
          # fi
          if (( $ANALYSIS < $ANALYSIS_MAX ))
          then
            echo Fail analysis section
            exit 1
          fi
          if (( $DEPENDENCIES < $DEPENDENCIES_MAX ))
          then
            echo Fail dependencies section
            exit 1
          fi
          if (( $NULL_SAFETY < $NULL_SAFETY_MAX ))
          then
            echo Fail null_safety section
            exit 1
          fi
